/**
 * @file     Sensor.h
 * @brief    LM35 temperature sensor driver interface
 * @details 
 * This module provides an abstraction layer for acquring and
 * processing temperature data from an LM35 analog temperature sensor
 * connected to STM32 adc peripheral.
 * Features:
 *  - LM35 driver initialization
 *  - ADC DMA acquisition
 *  - Circular DMA buffer management
 *  - Half-tranfer and transfer-complete event handling
 *  - ADC sample averaging
 *  - ADC-to-voltage conversion
 *  - voltage-to-temperature conversion
 *  - Temperature validity checking
 *  - Sensor fault detection
 *  - Processed temperature data access
 * The driver depends on the STM32 HAL ADC interface.
 * The ADC peripheral, GPIO configuration, DMA configuration
 * and time trigger are assumed to be configured by STM32CubeMX.
 *
 *  - Sensor               : LM35
 *  - ADC                  : ADC1
 *  - ADC channel          : ADC1_IN0
 *  - GPIO                 : PA0
 *  - ADC resolution       : 12-bit
 *  - VREF                 : 3.3 V
 *  - Sampling rate        : 100 Hz
 *  - DMA mode             : Circular
 * @author   Fatemeh Moghadasian
 * @version  1.2
 */

#ifndef SENSOR_LM35_H
#define SENSOR_LM35_H

 #include "stm32f4xx_hal.h"
 #include <stdbool.h>
 #include <stdint.h>


 /* Constant Parameter */

 /**
  * @brief ADC DMA buffer Size
  * The buffer is divided into two processing blocks:
  * [0  ... 15]  -> Half-transfer block
  * [16 ... 31]  -> Transfer-complete block
  */
#define SENSOR_ADC_BUFFER_SIZE   (32U)


/**
 * @brief ADC resolution maximum value
 * 12-bit ADC:
 *  2^12 - 1 = 4095
 */
 #define SENSOR_ADC_MAX_VALUE    (4095.0f)


 /**
  * @brief ADC reference voltge
  * STM32 ADC reference voltage for this project.
  */
#define SENSOR_ADC_VREF          (3.3f)


/**
 * @brief LM35 sensitivity
 * LM35 output:
 * 10 mV/°C
 * Therefore:
 * 0.010 V/°C
 */
#define SENSOR_LM35_SENSITIVITY  (0.010f)


/**
 * @brief Minimum valid application temperature
 * Temperatures outside this range are considered invalid
 * for the greenhouse application
 */
#define SENSOR_MIN_TEMPERATURE_C  (-20.0f)

/**
 * @brief Maximum valid application temperature
 * Temperatures outside this range are considered invalid
 * for the greenhouse application
 */
#define SENSOR_MAX_TEMPERATURE_C  (50.0f)

/**
 * @brief Maximum allowed number of consecutive missing 
 *        sensor updates before declaring a signal-loss fault
 * This value is used later by the safety layer
 */
#define SENSOR_MAX_MISSING_UPDATES  (10U)


/* Sensor Status */
/**
 * @brief Sensor operation status */
typedef enum
{
  SENSOR_STATUS_NO_DATA = 0U,
  SENSOR_STATUS_OK,                         /**< Valid sensor measurment */
  SENSOR_STATUS_OUT_OF_RANGE,               /**< Temperature is outside the valid applicaton range */
  SENSOR_STATUS_SIGNAL_LOST                 /**< ADC/DMA data is not being updated */
} Sensor_Status_t;

/* Sensor Event */
/**
 * @brief ADC DMA processing event
 * This enum represents events generated by the ADC DMA callbacks.
 */
typedef enum
{
  SENSOR_EVENT_NONE = 0U,          /**< No event */
  SENSOR_EVENT_HALF_COMPLETE,      /**< ADC DMA half-transfer complete event */
  SENSOR_EVENT_COMPLETE            /**< ADC DMA transfer complete event */
} Sensor_Event_t;

/* Sensor Data Structure */
/**
 * @brief Processed sensor measurment
 * This structure holds the processed temperature data from the LM35 sensor.
 */
typedef struct
{
  uint16_t        adc_raw;              /**< Averaged raw ADC value */
  float           voltage_v;            /**< Converted voltage value */
  float           temperature_c;        /**< Converted temperature value */
  Sensor_Status_t status;               /**< Sensor operation status */
} Sensor_Data_t;

/* Function Prototypes */

/**
 * @brief  Initialize the LM35 sensor driver
 * @param  hadc Pointer to the ADC handle configured by CubeMX
 * @return HAL status
 * @note
 * The ADC peripheral, GPIO, DMA and timer trigger must already
 * be initialized before callling this function
 */
HAL_StatusTypeDef Sensor_Init(ADC_HandleTypeDef *hadc);

/**
 * @brief  Start ADC DMA apquisition
 * @return HAL status
 * @note
 * ADC DMA operates in circular mode
 */
HAL_StatusTypeDef Sensor_Start(void);

/**
 * @brief  Notify the driver about ADC DMA half-transfer.
 * This function should be called from:
 *   HAL_ADC_HalfConvCpltCallback()
 * @note
 * This function executes in interrupt context and therefore
 * must remain short and non-blocking.
 */
void Sensor_DMA_HalfCompleteCallback(void);


/**
 * @brief  Notify driver about ADC transfer-complete event
 * This function is called from HAL_ADC_ConvCpltCallback()
 */
void Sensor_DMA_CompleteCallback(void);


/**
 * @brief Process available ADC samples
 * This function performs:
 *  - ADC block averaging
 *  - ADC-to-voltage conversion
 *  - voltage-to-temperature conversion
 *  - Sensor validity checking
 * @note
 * This function is non-bloking
 */
void Sensor_Process(void);


/**
 * @brief  Get the latest sensor data
 * @return Sensor_Data_t containing the latest measurment
 */
Sensor_Data_t Sensor_GetData(void);

/**
 * @brief  Check whether new sensor data is available
 * @return true if new data is available, false otherwise
 */
bool Sensor_DataReady(void);

/**
 * @brief  Check whether the sensor is currenty valid
 * @return true if sensor status is SENSOR_STATUS_OK, false otherwise
 */
bool Sensor_IsValid(void);


/**
 * @brief  Get current sensor status
 * @return Current Sensor_Status_t value
 */
Sensor_Status_t Sensor_GetStatus(void);


 #endif /* SENSOR_LM35_H */