/**
 * @file     fan.h
 * @brief    DC fan PWM driver interface
 * @details
 * This module provides an abstraction layer for controlling
 * a DC fan using a PWM signal generated by an STM32 timer.
 * Features:
 *  - Fan driver initialization
 *  - PWM output start and stop
 *  - Fan ON/OFF control
 *  - Fan speed control in percent
 *  - PWM duty-cycle calculation
 *  - Current fan state access
 *  - Current fan speed access
 *  - Driver status access
 *  - Complete fan data access
 *  - Safe shutdown
 * The driver depends on the STM32 HAL TIM interface.
 * The timer and PWM GPIO configuration are assumed to be
 * configured by STM32CubeMX before the driver is initialized.
 * Hardware configuration for this project:
 *  - PWM Timer   : TIM3
 *  - PWM Channel : TIM_CHANNEL_1
 * The driver does not contain application-level control logic.
 * Temperature thresholds, FSM decisions and safety policies
 * belong to the application/control layer.
 * @author   Fatemeh Moghadasian
 * @version  1.4
 */

#ifndef FAN_H
#define FAN_H


#include "stm32f4xx_hal.h"
#include <stdbool.h>
#include <stdint.h>



/* Fan Configuration */

/**
 * @brief Minimum allowed fan speed.
 * 0% corresponds to zero PWM duty cycle.
 */
#define FAN_MIN_SPEED_PERCENT       (0U)


/**
 * @brief Maximum allowed fan speed.
 * 100% corresponds to maximum PWM duty cycle.
 */
#define FAN_MAX_SPEED_PERCENT       (100U)


/**
 * @brief Default fan speed after initialization.
 * The fan starts in the OFF state with 0% speed.
 */
#define FAN_DEFAULT_SPEED_PERCENT   (0U)



/* Fan State */

/**
 * @brief Logical fan operating state.
 * These values represent the software state of the fan.
 * They are independent of the timer/PWM hardware.
 */
typedef enum
{
    FAN_OFF = 0U,       /**< Fan is OFF */
    FAN_ON  = 1U        /**< Fan is ON  */
} Fan_State_t;



/* Fan Status */

/**
 * @brief Fan driver status.
 */
typedef enum
{
    FAN_STATUS_NOT_INITIALIZED = 0U,  /**< Driver not initialized */
    FAN_STATUS_OFF,                  /**< Fan is OFF */
    FAN_STATUS_ON,                   /**< Fan is ON */
    FAN_STATUS_INVALID              /**< Invalid command/configuration */
} Fan_Status_t;



/* Fan Data */

/**
 * @brief Complete fan state information.
 * This structure contains the latest logical and PWM information
 * maintained by the driver.
 */
typedef struct
{
    Fan_State_t  state;           /**< Current logical fan state */
    Fan_Status_t status;          /**< Current driver status */
    uint8_t      speed_percent;   /**< Requested speed: 0-100% */
    uint32_t     compare_value;   /**< Current PWM compare value */
    uint32_t     auto_reload;     /**< Timer ARR value */
} Fan_Data_t;



/* Function Prototypes */



/**
 * @brief Initialize the fan driver.
 * The driver stores the timer handle and PWM channel and
 * initializes the fan in a safe OFF state.
 * @param htim    Pointer to the timer handle configured by CubeMX.
 * @param channel PWM channel used by the fan.
 * @return
 *        HAL_OK   if initialization succeeds.
 *        HAL_ERROR if the timer handle is NULL or configuration
 *        is invalid.
 * @note
 * The timer must already be initialized by CubeMX.
 */
HAL_StatusTypeDef Fan_Init(TIM_HandleTypeDef *htim, uint32_t channel);


/**
 * @brief Start PWM generation.
 * Starts the configured PWM channel.
 * The fan is kept OFF initially by setting the compare value
 * to zero.
 * @return HAL status.
 */
HAL_StatusTypeDef Fan_Start(void);


/**
 * @brief Stop PWM generation.
 * The PWM compare value is first set to zero and then
 * the PWM channel is stopped.
 * @return HAL status.
 */
HAL_StatusTypeDef Fan_Stop(void);


/**
 * @brief Turn the fan ON.
 * The fan is turned ON using the currently configured
 * speed percentage.
 * @return HAL status.
 * @note
 * If the current speed is 0%, the function does NOT
 * automatically change it to 100%. The requested speed
 * remains under application control.
 */
HAL_StatusTypeDef Fan_On(void);


/**
 * @brief Turn the fan OFF.
 * Sets PWM duty cycle to zero while preserving the
 * previously requested speed percentage.
 * @return HAL status.
 * @example
 * Fan_SetSpeed(50);
 * Fan_Off();
 * Fan_On();
 * The fan will return to 50%.
 */
HAL_StatusTypeDef Fan_Off(void);


/**
 * @brief Set fan speed.
 * @param speed_percent Requested fan speed from 0 to 100%.
 * @return
 *        HAL_OK if accepted.
 *        HAL_ERROR if the driver is not initialized
 *        or speed is outside the valid range.
 * @note
 * Setting speed to 0% turns the fan OFF.
 * If the fan is currently ON, the new speed is applied
 * immediately.
 */
HAL_StatusTypeDef Fan_SetSpeed(uint8_t speed_percent);


/**
 * @brief Get current requested fan speed.
 * @return Speed in percent, from 0 to 100.
 */
uint8_t Fan_GetSpeed(void);


/**
 * @brief Get current fan logical state.
 * @return Current Fan_State_t.
 */
Fan_State_t Fan_GetState(void);


/**
 * @brief Get current fan driver status.
 *
 * @return Current Fan_Status_t.
 */
Fan_Status_t Fan_GetStatus(void);


/**
 * @brief Get complete fan data.
 * @return Fan_Data_t containing current fan information.
 */
Fan_Data_t Fan_GetData(void);


/**
 * @brief Check whether fan is currently ON.
 * @return
 *        true  -> fan is logically ON
 *        false -> fan is OFF
 */
bool Fan_IsOn(void);


/**
 * @brief Check whether fan is currently OFF.
 * @return
 *        true  -> fan is logically OFF
 *        false -> fan is ON
 */
bool Fan_IsOff(void);


/**
 * @brief Check whether the driver has been initialized.
 * @return
 *        true  -> initialized
 *        false -> not initialized
 */
bool Fan_IsInitialized(void);


/**
 * @brief Force the fan into a safe OFF state.
 * PWM duty cycle is immediately set to zero and the
 * internal state is updated to FAN_OFF.
 */
void Fan_SafeOff(void);


#endif /* FAN_H */